import Foundation
import SwiftData

typealias RakuenSubjectTopicCache = BangumiSchemaV2.RakuenSubjectTopicCacheV1
typealias RakuenGroupTopicCache = BangumiSchemaV2.RakuenGroupTopicCacheV1
typealias RakuenGroupCache = BangumiSchemaV2.RakuenGroupCacheV1
